AWSTemplateFormatVersion: 2010-09-09
Description: lake data domain, dev environment

Parameters:
    pPipelineReference:
        Type: String
        Default: none

Resources:
    rForecourt:
        Type: AWS::CloudFormation::Stack
        DeletionPolicy: Delete
        UpdateReplacePolicy: Delete
        Properties:
            TemplateURL: ./foundations-lake-dev.yaml
            Parameters:
                pPipelineReference: !Ref pPipelineReference

    rEngineering:
        Type: AWS::CloudFormation::Stack
        DependsOn: rForecourt
        DeletionPolicy: Delete
        UpdateReplacePolicy: Delete
        Properties:
            TemplateURL: ./team-lake-engineering-dev.yaml
            Parameters:
                pPipelineReference: !Ref pPipelineReference
            Tags:
                - Key: sdlf:team
                  Value: engineering
