AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Monitoring stack - SNS, CloudTrail, StorageLens, CloudWatch Dashboards, ELK, Budgets

Parameters:
  pKMSKeyId:
    Type: String
    Default: "{{resolve:ssm:/SDLF/KMS/KeyArn:1}}"

Resources:
  ######## SNS #########
  rSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: sdlf-notifications
      KmsMasterKeyId: !Ref pKMSKeyId

  rSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: sdlf-notifications
        Version: "2012-10-17"
        Statement:
          - Sid: sdlf-notifications
            Effect: Allow
            Principal:
              Service:
                - cloudtrail.amazonaws.com
                - cloudwatch.amazonaws.com
            Action: sns:Publish
            Resource: !Ref rSNSTopic
      Topics:
        - !Ref rSNSTopic