AWSTemplateFormatVersion: 2010-09-09
Description: Multi-environment CICD team repos resources in shared DevOps account

Parameters:
  pKMSKey:
    Description: The KMS key used by CodeBuild and CodePipeline
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/KMS/CICDKeyId
  pSdlfGitlabGroup:
    Type: String
    Default: sdlf
  pCicdRepository:
    Type: String
    Default: sdlf-cicd
  pCatalogRepository:
    Type: String
    Default: sdlf-catalog
  pFoundationsRepository:
    Type: String
    Default: sdlf-foundations
  pTeamRepository:
    Type: String
    Default: sdlf-team
  pPipelineRepository:
    Type: String
    Default: sdlf-pipeline
  pDatasetRepository:
    Type: String
    Default: sdlf-dataset
  pStageARepository:
    Type: String
    Default: sdlf-stageA
  pStageBRepository:
    Type: String
    Default: sdlf-stageB
  pDatalakeLibraryRepository:
    Type: String
    Default: sdlf-datalakeLibrary
  pUtilsRepository:
    Type: String
    Default: sdlf-utils
  pMainRepository:
    Type: String
    Default: sdlf-main
  pMonitoringRepository:
    Type: String
    Default: sdlf-monitoring
  pEnableMonitoring:
    Description: Build sdlf-monitoring cloudformation module as part of domain pipelines
    Type: AWS::SSM::Parameter::Value<String>
    Default: /SDLF/Monitoring/Enabled

Conditions:
  EnableMonitoring: !Equals [!Ref pEnableMonitoring, true]

Resources:
  ######## GITLAB #########
  rSdlfGitlabGroup:
    Type: GitLab::Groups::Group
    Properties:
      Name: SDLF
      Path: !Ref pSdlfGitlabGroup

  rCicdCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pCicdRepository
      Path: !Ref pSdlfGitlabGroup

  rCatalogCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pCatalogRepository
      Path: !Ref pSdlfGitlabGroup

  rFoundationsCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pFoundationsRepository
      Path: !Ref pSdlfGitlabGroup

  rTeamCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pTeamRepository
      Path: !Ref pSdlfGitlabGroup

  rPipelineCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pPipelineRepository
      Path: !Ref pSdlfGitlabGroup

  rDatasetCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pDatasetRepository
      Path: !Ref pSdlfGitlabGroup

  rStageACodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pStageARepository
      Path: !Ref pSdlfGitlabGroup

  rStageBCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pStageBRepository
      Path: !Ref pSdlfGitlabGroup

  rDatalakeLibraryCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pDatalakeLibraryRepository
      Path: !Ref pSdlfGitlabGroup

  rMainCodeCommit:
    Type: GitLab::Projects::Project
    Properties:
      Name: !Ref pMainRepository
      Path: !Ref pSdlfGitlabGroup

  rMonitoringCodeCommit:
    Type: GitLab::Projects::Project
    Condition: EnableMonitoring
    Properties:
      Name: !Ref pMonitoringRepository
      Path: !Ref pSdlfGitlabGroup

  rCicdCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/CicdCodeCommit
      Type: String
      Value: !GetAtt rCicdCodeCommit.Name
      Description: Name of the Cicd repository

  rCatalogCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/CatalogCodeCommit
      Type: String
      Value: !GetAtt rCatalogCodeCommit.Name
      Description: Name of the Catalog repository

  rFoundationsCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/FoundationsCodeCommit
      Type: String
      Value: !GetAtt rFoundationsCodeCommit.Name
      Description: Name of the Foundations repository

  rTeamCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/TeamCodeCommit
      Type: String
      Value: !GetAtt rTeamCodeCommit.Name
      Description: Name of the Team repository

  rPipelineCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/PipelineCodeCommit
      Type: String
      Value: !GetAtt rPipelineCodeCommit.Name
      Description: Name of the Pipeline repository

  rDatasetCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/DatasetCodeCommit
      Type: String
      Value: !GetAtt rDatasetCodeCommit.Name
      Description: Name of the Dataset repository

  rStageACodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/StageACodeCommit
      Type: String
      Value: !GetAtt rStageACodeCommit.Name
      Description: Name of the StageA repository

  rStageBCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/StageBCodeCommit
      Type: String
      Value: !GetAtt rStageBCodeCommit.Name
      Description: Name of the StageB repository

  rDatalakeLibraryCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/DatalakeLibraryCodeCommit
      Type: String
      Value: !GetAtt rDatalakeLibraryCodeCommit.Name
      Description: Name of the DatalakeLibrary repository

  rUtilsCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/UtilsCodeCommit
      Type: String
      Value: !Ref pUtilsRepository
      Description: Name of the Utils repository

  rMainCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SDLF/CodeCommit/MainCodeCommit
      Type: String
      Value: !GetAtt rMainCodeCommit.Name
      Description: Name of the main repository

  rMonitoringCodeCommitSsm:
    Type: AWS::SSM::Parameter
    Condition: EnableMonitoring
    Properties:
      Name: /SDLF/CodeCommit/MonitoringCodeCommit
      Type: String
      Value: !GetAtt rMonitoringCodeCommit.Name
      Description: Name of the monitoring repository
